### ISSUE TITLE
Adding Data Structures section in the code Book

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [Shreyaa173/Code-Book#10]
In code book i would love to add data structures section in which i will provide the description about various data structures and the resources.
 
This Section would really help in improving the code book
 
please assign me this work through l required labels through the gssoc'24 extended program

**Comment by Shreyaa173** [comment]
Make sure you star the repo for further proceeding.

**Comment by BVPKARTHIKEYA** [comment]
i have changed the description as i added the data structures section
![image](https://github.com/user-attachments/assets/cdbcd13f-dd0a-4ca1-8ef2-287e01daeec1)

Added Data structures section in code book
![image](https://github.com/user-attachments/assets/0904deb5-de16-4e05-ab24-5c9d95ef3628)
