### ISSUE TITLE
Incomplete signin and login page and inproper email id incomlete tutorials 

### ISSUE THREAD

**Issue by lakshmirajvagu** [Shreyaa173/Code-Book#102]
i want to add sign in and login page which directs to a sign in page and want to modify the email addrees that given at the end of the web site and link the tutorials to the best youtube videos 
![Screenshot 2024-10-07 151142](https://github.com/user-attachments/assets/81a0e003-0de1

https://github.com/user-attachments/assets/f040d3ba-bd64-4061-8d68-b66a6dea3874

-4829-8f46-04a658cdbaca)

please assign me this issue @Shreyaa173

**Comment by Shreyaa173** [comment]
Assigned to you

**Comment by lakshmirajvagu** [comment]
please add level 3  hacktoberfest and gssoc labes  @Shreyaa173

**Comment by lakshmirajvagu** [comment]
@Shreyaa173 please check the pr #116
