### ISSUE TITLE
UI Design and Input Validation Issues on  'Contact Page'

### ISSUE THREAD

**Issue by Preethii-R** [Shreyaa173/Code-Book#106]
### **_I have identified few issues on the "Contact Us" page of the website that could impact user experience and data validation:_**

- **_UI Design_**: The layout and design of the form could be improved for a more polished and user-friendly experience. Currently, it feels a bit unrefined and could benefit from design enhancements to make it more appealing and accessible.

![Screenshot (8)](https://github.com/user-attachments/assets/94f0a0b5-8f71-43dc-a7b8-cb009abd59be)

- **_Email Validation_**: The email input box is not validating the email format properly. It is accepting invalid email addresses such as abc@GMAIL.com, which should ideally be rejected as per standard email validation practices.

- **_Phone Number Input_**: The phone number input field does not have any restrictions on the number of digits, allowing users to input excessively long numbers. Implementing a limit would help improve data integrity. 

![Screenshot (9)](https://github.com/user-attachments/assets/730b1776-a1df-4646-bbae-c70a46980c21)

**Comment by Shreyaa173** [comment]
assigned to you
