### ISSUE TITLE
Add pdf Books links for specific course 

### ISSUE THREAD

**Issue by Kiran-Jadhav200** [Shreyaa173/Code-Book#126]
I would like to add a pdf book link to the specific course from where they can download 
Assign this issue to me under  GSSoC'24-Extd contributor

**Comment by Shreyaa173** [comment]
assigned to you

**Comment by Kiran-Jadhav200** [comment]
Thank you for assign I will complete it

**Comment by ashutoshak5386** [comment]
Can you please assign me this issue i want to work on it .
