### ISSUE TITLE
Add "TypeScript" Course to the Platform

### ISSUE THREAD

**Issue by SCR01** [Shreyaa173/Code-Book#13]
Currently, there is a gap in the platform’s offering of courses, particularly for TypeScript, which is a superset of JavaScript and growing in demand for modern web development projects. Adding a TypeScript course would complement the JavaScript course and help learners advance their skills in writing scalable, maintainable code.

Developers who are already familiar with JavaScript and want to enhance their skill set in writing strongly typed, error-proof code.

Given the popularity of TypeScript in the industry and its importance in modern development, adding this course would significantly enhance the platform’s value.

**Comment by Injamul2k24** [comment]
Could you assign  me for this
