### ISSUE TITLE
Making website Responsive

### ISSUE THREAD

**Issue by Dishika18** [Shreyaa173/Code-Book#150]
As of now the website is not responsive on phone and tablet view. I'll make the website responsive including its navbar and  body.
Please assign this issue to me under `gssoc-ext` & `Hacktoberfest`. 

Unresponsive Website:

![Screenshot 2024-10-12 211134](https://github.com/user-attachments/assets/b0b5a192-e5de-43d2-9e36-9fa2d4461070)

**Comment by Shreyaa173** [comment]
assigned to you
