### ISSUE TITLE
#can add roadmap section at navbar

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [Shreyaa173/Code-Book#156]
add another webpage having various roadmaps for different career paths. like for frontend, backend, full stack, MERN, Devops, AWS etc

**Comment by Shreyaa173** [comment]
assigned to you

**Comment by SanikaBhalerao1345** [comment]
Is it ok if I link carrer paths to roadmap.sh webpage career paths

**Comment by Shreyaa173** [comment]
Yeah

**Comment by SanikaBhalerao1345** [comment]
@Shreyaa173 and also where can i find main HTML page content in the code? can u pls guide me

**Comment by Shreyaa173** [comment]
It's react based so all the things are from different jsx file. There names are according to their work you can refer to them. They are in src folder

**Comment by SanikaBhalerao1345** [comment]
hi @Shreyaa173 the code-book webpage looks disoriented (maybe due to login ), bcz of this I'm having some trouble adding roadmap section in an oriented manner. can you pls check once
thanks

**Comment by Shreyaa173** [comment]
No need Closing it as of now
