### ISSUE TITLE
Change the UI of contact us

### ISSUE THREAD

**Issue by Ishika-Gupta06** [Shreyaa173/Code-Book#179]
![Screenshot 2024-10-14 234537](https://github.com/user-attachments/assets/4669cd36-1ee1-4e36-a98d-1f665c0e2286)
To add a systematic visual to contact us

**Comment by Ishika-Gupta06** [comment]
@Shreyaa173 
assign me under gssoc-ext, hacktoberfest & levl-1,2,3

**Comment by Shreyaa173** [comment]
No need
