### ISSUE TITLE
 Login and Signup Page with Authentication

### ISSUE THREAD

**Issue by saras-69** [Shreyaa173/Code-Book#185]
Description
We need to create a login and signup page that includes authentication functionality. This feature will allow users to register for an account and securely log in, improving user management and security within the application.

Steps to Reproduce the Issue
To assist us in understanding and resolving the issue, please outline the steps you took that led to the problem:

Action 1: Navigate to the home page or landing page.
Action 2: Attempt to access a restricted page that requires authentication.
Action 3: Observe that users are prompted to log in or sign up if they are not authenticated.
Feel free to be as detailed as necessary so we can replicate the issue accurately.

Expected Behavior
Users should be able to register for a new account via the signup page and log in with their credentials on the login page. Upon successful authentication, users should be redirected to their dashboard or homepage.

Actual Behavior
Currently, there is no dedicated login or signup page available for user authentication.

**Comment by Shreyaa173** [comment]
Assigned to you

**Comment by harshbhar0629** [comment]
Can i work on this issue??

**Comment by harshbhar0629** [comment]
@saras-69 Backend portion?? Then how will you manage authentication??

**Comment by saras-69** [comment]
@harshbhar0629 yo manage authentication and the backend portion need to set up a backend server that Handles authentication related task.

**Comment by saras-69** [comment]
Or use third-party authentication services like
Firebase, Amlify,  AWS ,

**Comment by harshbhar0629** [comment]
I agree but you mention in your issue authentication word it means you will be implementing login and signup functionality instead of its UI portion.

**Comment by harshbhar0629** [comment]
I'm just asking otherwise i will create a issue for backend functionality:)
