### ISSUE TITLE
[enhancement]: Add Dark and light mode functionality

### ISSUE THREAD

**Issue by faiz66388** [Shreyaa173/Code-Book#187]
Description:
It would be beneficial to add a toggle for Dark and Light mode in the application. This feature will improve user experience by allowing users to switch between themes based on their preferences or system settings. A Dark mode can help reduce eye strain, especially in low-light environments, while Light mode is preferred during the day or in bright settings.

Steps to Reproduce:
Navigate to the homepage of the application.
Look for a setting to toggle between Dark and Light modes.
Notice that there is no option to switch themes.
Expected Behavior:
There should be a toggle or switch available in the settings or user interface that allows users to change between Dark and Light modes. The application should adapt accordingly based on the selection.

Actual Behavior:
Currently, there is no functionality to toggle between Dark and Light modes, and the user is limited to one theme throughout the application.

**Comment by Shreyaa173** [comment]
Assigned to you

**Comment by himanchal08** [comment]
Hi @Shreyaa173 ,

Could you please assign this issue to me? I would love to work on it. 
This is my darkmode toggle button sample [demo](https://dark-mode-pro.vercel.app/) . Please considering assigning this issue to me . 

Thank you!
Himanchal

**Comment by Shreyaa173** [comment]
Assigned to you also

**Comment by Shreyaa173** [comment]
The one who did it first I'll merge their PR

**Comment by Shreyaa173** [comment]
Things are not visible in the light theme. Correct it @faiz66388
