### ISSUE TITLE
Text not justify aligned on main page.

### ISSUE THREAD

**Issue by MimanshaKaur** [Shreyaa173/Code-Book#188]
Hii @Shreyaa173 

As you can see that the text on main landing page is not justify aligned so it is somewhere making it look a little unprofessional. 

![Screenshot 2024-10-15 145351](https://github.com/user-attachments/assets/d5f19b74-1259-4ead-90ec-679f506a787f)

![Screenshot 2024-10-15 145404](https://github.com/user-attachments/assets/bfa41029-b219-47d4-ac91-771f1fb16117)

![Screenshot 2024-10-15 145414](https://github.com/user-attachments/assets/fcd1ef2f-76c2-4398-b6ec-defc28798341)

So, to give it a professional look.. i am thinking to justify align this text.
@Shreyaa173 Hoping a positive response from your end.

**Comment by Shreyaa173** [comment]
It's good
