### ISSUE TITLE
Add icons to connect with us in footer instead of words

### ISSUE THREAD

**Issue by Annapoornaaradhya** [Shreyaa173/Code-Book#189]
I would like to add icons instead of 
![image](https://github.com/user-attachments/assets/e7728577-634f-438c-ad05-dd286428b4b2)

it would look like similar to this
![image](https://github.com/user-attachments/assets/4afba876-bb7b-4a81-a63e-f9c7662842f9)

@Shreyaa173 please assign me this issue under gssoc-ext and hactoberfest-accecpted

Thank you

**Comment by Shreyaa173** [comment]
Not needed
