### ISSUE TITLE
 Enhance Navbar Interactivity with Animations and Improved Button Styles

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [Shreyaa173/Code-Book#193]
**Summary of the Problem:**
The current navbar lacks animations and hover effects for the logo and nav items, making it less engaging. Additionally, the button styles need improvement to attract user attention.

## Expected Behavior
- The logo should have a hover effect or animation that enhances user interactivity.
- Nav items should feature more engaging animations on hover.
- Buttons in the navbar should have improved styling that grabs the audience's attention.

## Current Behavior
- The logo does not respond to user interactions (hover/animation).
- Nav items have minimal or ineffective animations that do not engage users.
- Button styles are basic and fail to stand out.

## Steps to Reproduce
1. Open the website.
2. Hover over the logo and nav items to observe the lack of animation and interactivity.
3. Examine the current button styles in the navbar.

 

## Additional Context
Improving the navbar's animations and button styles will create a more engaging user experience, encouraging users to interact with the site.

## Screenshot
![nav12](https://github.com/user-attachments/assets/63bca8f4-3971-4ba4-8ef2-27ccf8af4df0)

 
## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

**Comment by Shreyaa173** [comment]
Assigned to you
