### ISSUE TITLE
Enhance Contact Us Section with Improved Styling and Animations

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [Shreyaa173/Code-Book#194]
**Summary of the Problem:**
The current "Contact Us" section lacks visual appeal and engagement. The contact form needs better styling, and the icons for the phone, email, and location could use animations to make the section more impressive and engaging.

## Expected Behavior
- The contact form should have a more stylish design with improved input fields.
- Border animations should be added to the contact form for a modern look.
- The submit button should be enhanced in style to draw attention.
- Animations should be added to the call, mail, and location icons to increase user engagement.
- The "Contact Us" header should also have animations to grab users' attention.

## Current Behavior
- The contact form appears plain and uninviting.
- The submit button lacks distinctive styling.
- Icons for communication methods do not have animations, making them less engaging.
- The "Contact Us" header does not stand out visually.

## Steps to Reproduce
1. Open the website and navigate to the "Contact Us" section.
2. Observe the current styling of the contact form and submit button.
3. Note the lack of animations on the icons and the header.

 

## Additional Context
Enhancing the "Contact Us" section will improve the overall user experience, making it more inviting and interactive.
 
## Screenshot
 
![contactus2](https://github.com/user-attachments/assets/d919c8c5-a9e2-43b5-9b77-d8a3f567b585)

## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

**Comment by Shreyaa173** [comment]
Not needed as of now
