### ISSUE TITLE
Enhance Footer with Animations and Improved Styling

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [Shreyaa173/Code-Book#195]
**Summary of the Problem:**
The current footer lacks engaging elements, making it visually unappealing. The footer items need animation and hover effects, the "Code Book" logo should have an impressive hover effect, and the email search bar requires better styling to enhance user engagement.

## Expected Behavior
- Footer items should have animations and hover effects to create a more interactive experience.
- The "Code Book" logo should feature an eye-catching hover effect.
- The email input field should have improved styling to make it visually appealing and engaging.

## Current Behavior
- The footer items do not respond to user interactions, resulting in a static appearance.
- The "Code Book" logo does not have a hover effect, making it less engaging.
- The email search bar lacks stylish design elements, making it blend in with the background.

## Steps to Reproduce
1. Open the website and scroll down to the footer section.
2. Observe the current styling and lack of animations on footer items.
3. Check the "Code Book" logo for any hover effects.
4. Evaluate the styling of the email input field.

 

## Additional Context
Enhancing the footer with these changes will improve the overall user experience and make the website more engaging and visually appealing.

 ## Screenshot
![foot12](https://github.com/user-attachments/assets/2b45295c-0c1a-430a-b8a1-875ba3de3827)

## Labels
- **Type:** Enhancement
- **Priority:** Medium
- **Status:** Open
- **Area:** UI/UX

**Comment by Shreyaa173** [comment]
Not needed as of now
