### ISSUE TITLE
[BUG]: "Our Courses" Section - Responsive Layout Issues on Tablet and Mobile Devices

### ISSUE THREAD

**Issue by PrityanshuSingh** [Shreyaa173/Code-Book#197]
### Summary: 
The "Our Courses" section and course cards are not responsive on tablet and mobile devices, leading to a broken layout and poor user experience. This makes it difficult to navigate and interact with the content on smaller screens.

### Expected Behavior: 
The section should adapt smoothly to different screen sizes, with course cards resizing or reorganizing to maintain a user-friendly and visually appealing layout without any misalignments or cut-off content.

### Current Behavior:
- Layout breaks on tablet and mobile devices.
- Course cards are misaligned, with some content overlapping or cut off.
- The design is inconsistent, making it hard to browse the courses.

### Steps to Reproduce:
1. Navigate to the "Our Courses" section on the website.  
2. Resize the browser window to a tablet size (768px to 1024px wide) or a mobile size (320px to 767px wide).  
3. Check for any misaligned elements, overlapping content, or cut-off text in the "Our Courses" section and course cards.  

### Additional Context:
- Use CSS grids and media queries to create a responsive layout.
- Flexbox can also help achieve a more fluid design across different screen sizes.
- Adjust font sizes, padding, and margins for better readability on smaller screens.

### Screenshot:
1. 
![image](https://github.com/user-attachments/assets/b6f92ac3-b360-4967-8e04-64ba06d0a77b)

2. 
![image](https://github.com/user-attachments/assets/7c3e5b26-f41b-409a-987d-16d736bad6d4)

### Labels:
- Type: Enhancement  
- Priority: Medium  
- Status: Open  
- Area: UI/UX

@Shreyaa173  please assign me this issue under gssoc-ext and hactoberfest-accecpted

Thank you !

**Comment by Shreyaa173** [comment]
Already assigned to someone
