### ISSUE TITLE
[FEATURE] can make your website look dynamic

### ISSUE THREAD

**Issue by Vatsal-Verma** [Shreyaa173/Code-Book#198]
I would like to add scroll down animtaions in your wesbite which will not only make you website look catchy but more professional. I can do it for , You can assign this to me.

here is a sample : vatsport.netlify.app

**Comment by Vatsal-Verma** [comment]
> I would like to add scroll down animtaions in your wesbite which will not only make you website look catchy but more professional. I can do it for , You can assign this to me.

**Comment by Shreyaa173** [comment]
Assigned to you
