### ISSUE TITLE
Missing Deployment Link for the Project

### ISSUE THREAD

**Issue by Web-Dev-Learner** [Shreyaa173/Code-Book#2]
I would like to raise an issue regarding the absence of a deployment link for the project. A deployment link is crucial for users and contributors to easily access and interact with the application. Having a live demo available can significantly enhance user experience and encourage more contributions.

 Please provide a deployment link to a hosting service (e.g., GitHub Pages, Vercel, Netlify) where users can view the application live.

Please assign this issue to me as I would like to help in ensuring a deployment link is provided.
Please add relevant labels  GSSoC 2024 Extd

**Comment by pavitraag** [comment]
I would like to work on this. Please assign me under gssoc24.

**Comment by Shreyaa173** [comment]
Already Done thankyou for the suggestion
