### ISSUE TITLE
Features below" Contact us" are not working

### ISSUE THREAD

**Issue by PoojaKanagaraj06** [Shreyaa173/Code-Book#200]
![image](https://github.com/user-attachments/assets/c0b5894d-9c3a-49f2-88c4-bfeec8394cd2)
the social media reachability is needed as the page for social media is not directing, showing 404 error.
kindly assign me the issue @Shreyaa173 under gssoc'24 label

**Comment by Shreyaa173** [comment]
I'll do it by myself later
