### ISSUE TITLE
Make Website Fully Responsive with Hamburger Menu, Catchy Progress Bar, and Scroll Bar

### ISSUE THREAD

**Issue by srishti023** [Shreyaa173/Code-Book#201]
### **The website needs to be fully responsive, with the following enhancements:**

**Full Responsiveness:** Ensure all elements adjust for mobile, tablet, and desktop screens using media queries.

**Hamburger Menu:** Add a responsive hamburger menu for better navigation on smaller screens.

**Catchy Progress Bar:** Implement a progress bar that tracks page scroll and is visually appealing.

**Custom Scroll Bar:** Style the scroll bar to match the website theme and make it responsive.

### **current website lacks the responsiveness:**

https://github.com/user-attachments/assets/f94badb4-280e-427d-9c0d-ab7ea0870a8e

**Comment by Shreyaa173** [comment]
Assigned to you

**Comment by srishti023** [comment]
Hey @Shreyaa173 @sanjay-kv
Please check my PR and if any further changes or improvement needed let me know! Else merge it in your repo. 

Best Regards.
Srishti

**Comment by srishti023** [comment]
@Shreyaa173 I guess the level3 tag has no space in between level and 3. the correct label is level 3 please correct this the score is not seen on my leaderboard! Please shreyaa! HELP!

**Comment by aslams2020** [comment]
merged https://github.com/sanjay-kv/Open-source-Practice/pull/1529
