### ISSUE TITLE
Add Nodemailer Functionality for "Contact Us" Section

### ISSUE THREAD

**Issue by rudrapratap63** [Shreyaa173/Code-Book#206]
**Description:**
We need to implement Nodemailer functionality to send emails when a user submits the "Contact Us" form. This feature will enable us to receive inquiries directly via email, enhancing our communication with users.

**Comment by rudrapratap63** [comment]
@shravya312, please assign this issue to me and add the labels: `gssoc-ext`, `hacktoberfest`, and `level3`.

**Comment by Shreyaa173** [comment]
Assigned to you

**Comment by rudrapratap63** [comment]
@Shreyaa173 please assign this issue to @harshbhar0629

**Comment by harshbhar0629** [comment]
@Shreyaa173 ??????????
