### ISSUE TITLE
Add  About Us Page 

### ISSUE THREAD

**Issue by rudrapratap63** [Shreyaa173/Code-Book#207]
We need an "About Us" page to give users a better understanding of our project, the team behind it, and our mission. This page will provide background information, project goals, and contact details.

**Comment by Shreyaa173** [comment]
Not needed

**Comment by rudrapratap63** [comment]
Hello @Shreyaa173! If you have any features you'd like to add to Code-Book, please let me know—I’d be happy to contribute!
