### ISSUE TITLE
Bug : Search Functionality for "Explore Courses" Not Working on Home Page

### ISSUE THREAD

**Issue by rudrapratap63** [Shreyaa173/Code-Book#208]
The search functionality in the "Explore Courses" section on the home page is currently not working as expected. Users are unable to search for courses, and no results are displayed upon entering keywords.

**Steps to Reproduce**
1. Go to the home page.
2. Locate the "Explore Courses" search bar.
3. Enter any keyword and hit "Search."

**Expected Behavior** 
Courses related to the entered keyword should display in the search results.

**Actual Behavior**
 No results are shown, or the page remains static without any changes.

**Comment by Shreyaa173** [comment]
Assigned to you
