### ISSUE TITLE
[ENHANCEMENT]: I want to create a sign up page for your website.

### ISSUE THREAD

**Issue by MimanshaKaur** [Shreyaa173/Code-Book#211]
As there is no sign up page created for this website so i want to design a theme based sign up page for all new Code-Book users.
The sign-up will include information like : 
- Full Name
- Email Address
- Phone Number
- Password
- Confirm Password

As beautifully designed sign up page with a form  like this👇

![Screenshot 2024-10-16 172028](https://github.com/user-attachments/assets/1d3c81e4-33d5-4af1-8b0a-0399f71d8dae)

I hope this will make your website more interactive and will give it a complete look.
@Shreyaa173  please assign me this task with gssoc-ext and hacktoberfest-accepted labels

**Comment by Shreyaa173** [comment]
Assigned to you

**Comment by MimanshaKaur** [comment]
@Shreyaa173  you closed this task? why?i am almost there
