### ISSUE TITLE
Improve image for card component

### ISSUE THREAD

**Issue by fluid111** [Shreyaa173/Code-Book#222]
Current image for the card component property is not set properly it is stretched and on different size the image is not set properly . I want to fix the property for the  image so that it is responsive and the image is properly displayed.

Normally

![Screenshot 2024-10-16 211317](https://github.com/user-attachments/assets/cee7b078-3651-4500-9268-48c3fd188d4a)

In different screen size

![Screenshot 2024-10-16 211422](https://github.com/user-attachments/assets/9190b222-b280-4061-867b-70eae2e9b72d)

**Comment by Shreyaa173** [comment]
Already assigned
