### ISSUE TITLE
Implement a RESPONSIVE DESIGN to ensure the website functions seamlessly and looks AESTHETICALLY pleasing across all screen sizes.

### ISSUE THREAD

**Issue by nikhleshmahato** [Shreyaa173/Code-Book#24]
I can fix this issue by making the website more  **RESPONSIVE** and better looking. I will make sure it works well on all devices and looks good too. Please assign this issue to me, and I’ll start working on it right away!

**Comment by Shreyaa173** [comment]
assigned you
