### ISSUE TITLE
Feat: Login and Signup Backend

### ISSUE THREAD

**Issue by harshbhar0629** [Shreyaa173/Code-Book#241]
There is no login and signup functionality in website, also no database managed.

@Shreyaa173 Please assign this issue to me i will add the backend functionality for login and signup in your website.

Please assign this issue to under **gssoc-ext. level-3, hacktoberfest-accepted**.

**Comment by harshbhar0629** [comment]
@Shreyaa173 ??

**Comment by harshbhar0629** [comment]
@Shreyaa173 ??

**Comment by harshbhar0629** [comment]
@Shreyaa173 ??

**Comment by harshbhar0629** [comment]
@Shreyaa173 ??

**Comment by Shreyaa173** [comment]
Already assigned
