### ISSUE TITLE
BUG: Cards link

### ISSUE THREAD

**Issue by harshbhar0629** [Shreyaa173/Code-Book#242]
When user click on card then it navigates to youtube link but instead of youtube link when user click on cards it will navigates to its official documentation of cards content like if i click to css then it will be navigates to w3schools for css property same for html, when we click on C++ then it navigates to cppreference documentation of C++.

@Shreyaa173 Please assign this issue to me:)

**Comment by harshbhar0629** [comment]
@Shreyaa173 ??

**Comment by Shreyaa173** [comment]
Already assigned
