### ISSUE TITLE
Add a docker file

### ISSUE THREAD

**Issue by sanjay14073** [Shreyaa173/Code-Book#254]
Add a docker file to serve the application through docker.Docker is a popular platform used to package and run applications in containers. It provides a way to isolate applications from each other and the underlying system, ensuring that they run consistently across different environments.I would like to get the issue assigned under the hacktober accepted and gssoc-ext label

**Comment by sanjay14073** [comment]
@Shreyaa173 I would like to get the issue assigned to me

**Comment by Shreyaa173** [comment]
not needed
