### ISSUE TITLE
Feat : Add Animation on cards.

### ISSUE THREAD

**Issue by Adityadhiman0** [Shreyaa173/Code-Book#260]
I want to add some animation on cards.
![Screenshot (51)](https://github.com/user-attachments/assets/7e1dd2da-8a7a-4f77-8682-d0d01faabbb7)

**Comment by Adityadhiman0** [comment]
Please assign this issue to me. I want to work on your project.

**Comment by Adityadhiman0** [comment]
Please assign this issue to me.

**Comment by Shreyaa173** [comment]
Not needed
