### ISSUE TITLE
Bug: there are some extra boxes on back side of "Why choose us section".

### ISSUE THREAD

**Issue by Adityadhiman0** [Shreyaa173/Code-Book#263]
there are some extra boxes on back side of "Why choose us section". They should not be there.
![Screenshot 2024-10-17 230754](https://github.com/user-attachments/assets/cf4f8f05-97d7-4900-aaf6-ee2b4707ab64)

**Comment by Adityadhiman0** [comment]
Please assign this issue to me.

**Comment by DevROHIT11** [comment]
i want to work on this could you plz assign this to me

**Comment by Adityadhiman0** [comment]
please assign me this issue.
