### ISSUE TITLE
Feat: Add some animation in home page.

### ISSUE THREAD

**Issue by Adityadhiman0** [Shreyaa173/Code-Book#264]
I want to add some animations on the image on landing page page.
![Screenshot 2024-10-17 225651](https://github.com/user-attachments/assets/f885e707-cba2-439a-8622-95e82ba92f3c)

**Comment by Adityadhiman0** [comment]
Please assign this issue to me.

**Comment by BlossomBreeze25** [comment]
> Please assign this issue to me.

Can i work with you on this ?
