### ISSUE TITLE
There is no privacy-policy& terms page for the links in the footer

### ISSUE THREAD

**Issue by Vaishh18** [Shreyaa173/Code-Book#269]
![Screenshot 2024-10-18 193521](https://github.com/user-attachments/assets/90f92d7f-e5e5-44b9-8ce6-1543d2614cba)

![Screenshot 2024-10-18 193425](https://github.com/user-attachments/assets/411d697f-b269-4cf4-ab60-b75b484f3582)

@Shreyaa173 please assign me this issue under gssoc-ext

**Comment by Shreyaa173** [comment]
Assigned to you
