### ISSUE TITLE
Redirect the our courses  section to youtube channels

### ISSUE THREAD

**Issue by ash-k121** [Shreyaa173/Code-Book#28]
Redirecting the our courses  section to youtube channels which would actually be helpful
Please assign this issue to me under gssoc-ext 24 and hacktoberfest
![image](https://github.com/user-attachments/assets/2d4f3b69-8243-422a-8587-8bab2f1b6feb)

**Comment by Devanshu1603** [comment]
please assign this to me under gssoc ext level. will feel happy to contribute.

**Comment by Rashmi885** [comment]
Pls assign to me as I am interested to work on this
