### ISSUE TITLE
To create a responsive design and styling for the course cards and enable them to redirect to YouTube channels

### ISSUE THREAD

**Issue by shravya312** [Shreyaa173/Code-Book#29]

**Comment by Ibrangrd** [comment]
I will do it . As i have experience on it . Give me a chance

**Comment by Shreyaa173** [comment]
Assigned to @shravya312

**Comment by shravya312** [comment]
Hi @Shreyaa173  Thank you for assigning this task to me. Kindly can you add the labels gssoc-extd, hacktoberfest-accepted and level-2.

**Comment by shravya312** [comment]
I have done the pr for this issue @Shreyaa173
