### ISSUE TITLE
Feat: CI-CD Workflow

### ISSUE THREAD

**Issue by harshbhar0629** [Shreyaa173/Code-Book#296]
There is no CI-CD Workflow in this repo.

What CI-CD did??
A CI/CD workflow on GitHub automates the process of building, testing, and deploying code. When changes are pushed to the repository, GitHub Actions triggers the workflow, starting with building the code, running tests, and performing quality checks. If the tests pass, the code can be deployed to a staging or production environment. Notifications are sent to inform stakeholders about the workflow's success or failure.

@Shreyaa173 Please assign this issue to me with label:)

**Comment by Shreyaa173** [comment]
Not needed
