### ISSUE TITLE
Improve UI of Contact Us Page

### ISSUE THREAD

**Issue by Ankul8471** [Shreyaa173/Code-Book#298]
The current Contact Us page design could benefit from enhancements to improve user experience and visual appeal. The form elements (name, email, phone number, and message) could be better aligned and spaced for clarity. Adding hover effects, placeholders, and form validation can increase interactivity and usability. Additionally, the contact information (phone, email, address) could be formatted with icons to make the layout more engaging and readable. Improving the contrast and adjusting the padding/margins will help achieve a cleaner and more modern look. These updates will provide a more professional and user-friendly interface.
![Screenshot 2024-10-20 090856](https://github.com/user-attachments/assets/b21d2723-99bd-49d4-b34f-6c1f405509ff)

**Comment by Ankul8471** [comment]
@Shreyaa173 . hello please assign me this issue

**Comment by Lakshita-Kumawat** [comment]
@Shreyaa173 I would like to work on this issue

**Comment by aahanajena** [comment]
@Shreyaa173 i would like to fix this issue, I have good knowledge of UI designs
