### ISSUE TITLE
Migrate the codebase to react.

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [Shreyaa173/Code-Book#3]
Currently having html,css and js files makes it difficult to manage
Solution:
Moving to a framework like React  can be helpful and easy to maintain the codebase.
Please assign the issue  to me.

**Comment by Shreyaa173** [comment]
You can start your work

**Comment by Shreyaa173** [comment]
Make sure you star the repo for further proceeding.

**Comment by Vaibhav-Kumar-K-R** [comment]
The deployment link is not accessible and asks for authentication .
Please have a look into it .

**Comment by Vaibhav-Kumar-K-R** [comment]
I have linked a pull request referenced #31 .
Please review it.
