### ISSUE TITLE
README Update: Visual Enhancements , Fostering Contact Channel and enabling Contributors List

### ISSUE THREAD

**Issue by Varunshiyam** [Shreyaa173/Code-Book#305]
- To enhance communication and provide direct access to Project Guidance, I plan to include a dedicated Contact section 👤. This section will feature the LinkedIn and GitHub profiles of each mentors and Admin⚡️ enabling contributors to readily connect with them and address any project-related queries. 

- Additionally, to improve readability and organization, I Planned to implement clear visual separations between each section of the contributor documentation, ensuring a user-friendly and easily navigable 🚏 experience. 

- To effectively convey the essence of our project and its objectives, I propose creating a customized cover image for the repository.

- To foster a welcoming 🙏🏻 and inclusive environment, I will incorporate personalized welcome messages for our Repository.

- Finally, I would like to add a Contributors List which displays our talented Contributors.

+ Kindly Assign me this Issue Under 🌸Gssoc, ☘️hacktoberfest . I'm grateful to work with Talented Crews✨

**Comment by Shreyaa173** [comment]
Not needed
