### ISSUE TITLE
chatbot not working

### ISSUE THREAD

**Issue by amanver45** [Shreyaa173/Code-Book#308]
i want to fix chatbot
![Screenshot 2024-10-21 230215](https://github.com/user-attachments/assets/718c703b-8306-43e0-9394-b843e98c20f6)

**Comment by Shreyaa173** [comment]
It's working

**Comment by amanver45** [comment]
![Screenshot_2024-10-23-15-45-06-837_com android chrome](https://github.com/user-attachments/assets/85fe38bc-32a8-4be0-9de3-92cb9497697b)
Only reply for hi it's not working @Shreyaa173

**Comment by amanver45** [comment]
@Shreyaa173  check this
