### ISSUE TITLE
add rating to this website

### ISSUE THREAD

**Issue by VaralakshmiMaddireddy** [Shreyaa173/Code-Book#32]
As i am new to gssoc-extd  assign me to add rating to this website so that new users can attract to this website

**Comment by Ibrangrd** [comment]
I also work on my own project and also add rating . So, i can do it more effectively.

**Comment by VaralakshmiMaddireddy** [comment]
@Ibrangrd as this is my first issue i found. so ,i am excited to contribute.

**Comment by Ibrangrd** [comment]
@Shreyaa173 will assign . I am not .
