### ISSUE TITLE
[BUG] Navigation is not working , its not redirecting to home

### ISSUE THREAD

**Issue by Pheonixrog** [Shreyaa173/Code-Book#322]
https://github.com/user-attachments/assets/a7874c44-7a2d-4e19-95ab-775e63eeefdf

After clicking on courses, it never goes back to the home page. There is some error in the navigation as You can see in the video.

**Comment by Pheonixrog** [comment]
@Shreyaa173 please assign this to me

**Comment by Shreyaa173** [comment]
Already assigned
