### ISSUE TITLE
[UI] Fixing search Icon

### ISSUE THREAD

**Issue by Pheonixrog** [Shreyaa173/Code-Book#323]
The Search icon can be inside the search box or we can give little margin between search box and the icon , and also can change the color of the icon .
![Screenshot 2024-10-23 154306](https://github.com/user-attachments/assets/e6cbd53b-8f30-42a2-934d-5e855b7f239b)

**Comment by Pheonixrog** [comment]
@Shreyaa173 Assign this to me

**Comment by cypher4802** [comment]
@Shreyaa173 I am keen to to work on this issue can u pls assign to me and add hacktoberfest label

**Comment by Shreyaa173** [comment]
Already assigned
