### ISSUE TITLE
Enhance: UI Update

### ISSUE THREAD

**Issue by hgjajoo** [Shreyaa173/Code-Book#346]
Planning to update the UI for the section in image below
![image](https://github.com/user-attachments/assets/bf6111c6-c3c3-4d9b-a434-d622082c02bb)

can instead have something like image below
![image](https://github.com/user-attachments/assets/3ffe115e-5825-4041-96d6-25e2648b72f4)
will have a proper banner and design!

**Comment by Shreyaa173** [comment]
not needed
