### ISSUE TITLE
UI: Removing Extra elements

### ISSUE THREAD

**Issue by hgjajoo** [Shreyaa173/Code-Book#347]
![image](https://github.com/user-attachments/assets/aa2fec0b-04b2-4ab4-830c-1dcaa2f133f7)

Remove this footer since it serves no purpose, all links just redirect to '#'.
Can instead make a more simplistic Footer with just the link to the github repository of this project.

![image](https://github.com/user-attachments/assets/f31e66c4-6a3e-42ae-beea-86d32c2cc957)

same thing as above for form, looks like all this content is just copy pasted from a ui library. can completely remove this part, you dont need a Contact Us page for this project.

**Comment by Shreyaa173** [comment]
They are not functional as of now but they will be functional
