### ISSUE TITLE
Feature:to_make_buttons_look_more_appealing

### ISSUE THREAD

**Issue by piyahub** [Shreyaa173/Code-Book#348]
The buttons do not appear appealing to me, the UI could be changed, and it could be done better. Before hovering onto the buttons the page does not appeal to me if the buttons UI changed to some sort of 3-D it would look much better.
![Screenshot 2024-10-24 235346](https://github.com/user-attachments/assets/b535c138-9497-4d23-b57a-843018b89f42)

**Comment by Shreyaa173** [comment]
not needed
