### ISSUE TITLE
[Documentation] Add Table to Display Repository Statistics in README.md

### ISSUE THREAD

**Issue by KGupta2601** [Shreyaa173/Code-Book#354]
Issue Description:
The issue involves adding a well structured table to display repository statistics, such as the number of stars, forks, issues, and pull requests, directly in the README.md file. This will help contributors and users track the activity and contributions at a glance.

Steps to Implement:
Create a table in the README.md file displaying the following repository statistics:
Stars
Forks
Open Issues
Open Pull Requests
Closed Pull Requests
Use markdown syntax to include badges or icons for each statistic.
Add dynamic links to the corresponding sections of the repository for easy access (e.g., link to the "Issues" or "Pull Requests" tabs).
Expected Behavior:
The README.md file will contain a neatly formatted table that displays real-time repository statistics, making the repository's activity more visible and engaging for contributors and users.

Screenshot (for reference):
![379103314-6c04cef6-2926-40b9-a18a-9bee50d63026](https://github.com/user-attachments/assets/8e439a03-b69f-4ee8-b455-d6f79a1a2e02)
@Shreyaa173 kindly assign me this issue with labels of gssoc extended,hacktoberfest and level

**Comment by Shreyaa173** [comment]
Already assigned
