### ISSUE TITLE
UI Enhancement: Improve Course Card Layout and Responsiveness

### ISSUE THREAD

**Issue by Aman-Jangid** [Shreyaa173/Code-Book#366]
**The course cards on the "Our Courses" page have a few layout issues that impact the look and usability of the site, there is also lack of spacing between some sections and the site isn't properly responsive on all devices.**

**Issues :** 

- Text Alignment: Text inside the cards isn’t aligned properly.
- Responsiveness: The layout doesn’t adjust well on different screen sizes; things overlap or get cut off on smaller devices and width of course cards decreases on bigger screens.
- Image Scaling: Images in the course cards are stretched or don’t fit right.

![Screenshot_20241026_153702](https://github.com/user-attachments/assets/acf6046d-cc36-46e5-85ac-6794e08bd987)
![photo-collage png](https://github.com/user-attachments/assets/285793fa-d983-4dd2-b2ad-65575dc44bec)

**Proposed Fixes :**

- Add Spacing: Add consistent padding/margins between sections so the content doesn’t feel crowded.
- Fix Text Alignment: Align text consistently (center or left-aligned) to improve readability.
- Improve Responsiveness: Use media queries to ensure the layout works on mobile, tablet, and desktop views without overlap.
- Fix Image Scaling: Set the correct aspect ratio for images, so they display properly within each card and use SVGs where possible.

I’d like to work on this issue for Hacktoberfest. Could you please assign it to me?

**Comment by Shreyaa173** [comment]
Assign to you

**Comment by muskiagrwal** [comment]
i want to contribute on this project please assign me this prject
