### ISSUE TITLE
 💥Feature Request: Rotating Placeholder Text

### ISSUE THREAD

**Issue by akash70629** [Shreyaa173/Code-Book#379]
## Description:
Currently, the search bar placeholder text remains static. To enhance user engagement and provide a more dynamic experience, we propose introducing a rotating placeholder text feature.

## Requirements:

- Update the search bar placeholder text every 3 seconds.
- Display a list of predefined placeholder texts related to programming languages, frameworks, and tools.
- Ensure smooth text transitions.

## Here is the demo view

https://github.com/user-attachments/assets/c440f0fa-b2b2-4005-ba9d-0d9eee8efa63

## **Please checkmark the following checklist**

- [x] I ensured that a similar issue is not opened.
- [x] I provided a clear description of the problem.
- [x] I included steps to reproduce the issue.
- [x] I attached relevant context (screenshot).
- [x] I want to work on this issue.
- [x] I am a gssoc participant.

**Comment by akash70629** [comment]
Please assign me this issue .

**Comment by Shreyaa173** [comment]
Assign to you

**Comment by muskiagrwal** [comment]
i want to work on this project.please assign me this project

**Comment by akash70629** [comment]
> i want to work on this project.please assign me this project

She already assigned me 😅 already I linked a PR , waiting to merge .😅

**Comment by akash70629** [comment]
@Shreyaa173  why level 1 ?😕

**Comment by akash70629** [comment]
@Shreyaa173 Please reply !

**Comment by akash70629** [comment]
@Shreyaa173 hey !!!

**Comment by akash70629** [comment]
> @Shreyaa173 why level 1 ?😕Please make it level 2

@Shreyaa173 !!!
