### ISSUE TITLE
BUG: No Confirm Password field in Signup-Form

### ISSUE THREAD

**Issue by harshbhar0629** [Shreyaa173/Code-Book#392]
There is no confirm password field in Signup form. It may be possible user want to enter some password but anyother key pressed but he/she thinking I'm entering correct password for safety purpose confirm password field required.

![password](https://github.com/user-attachments/assets/a1011567-95e8-4448-9fbc-4652d2f87e35)

@Shreyaa173 Please assign this issue to me.

**Comment by Shreyaa173** [comment]
Assign to you
