### ISSUE TITLE
All Input forms validation

### ISSUE THREAD

**Issue by harshbhar0629** [Shreyaa173/Code-Book#393]
In login and signup there is no validation in input user can enter 1@gmail.com this is not valid email but your project support this validation which is wrong!

@Shreyaa173 Please assign this issue to me:)

**Comment by Shreyaa173** [comment]
Assign to you

**Comment by harshbhar0629** [comment]
@Shreyaa173 Please assign level-2 i will implement all forms validation either in contactUs, login, Signup and every field!
