### ISSUE TITLE
Feature Request: Detailed Help Center and FAQ

### ISSUE THREAD

**Issue by sezallagwal** [Shreyaa173/Code-Book#398]
#### Description
Implement a Help Center and FAQ section in the Truth-Tunnel application to provide new users with guidance, tutorials, and troubleshooting information. This will improve user experience by making it easier for users to navigate the app and resolve common issues independently.

#### Proposed Features
- **FAQ Section:** Address frequently asked questions about using the app, security, and privacy policies.
- **Search Functionality:** Allow users to search the Help Center for specific topics or keywords.

#### Tasks
1. **Content Creation:** Develop content for FAQs.
2. **UI/UX Design:** Create a clean, accessible interface for the Help Center section.
3. **Search Implementation:** Add a search bar for easy navigation within the Help Center.
4. **Mobile Compatibility:** Ensure the Help Center is optimized for mobile devices.

#### Benefits
- Reduces user frustration by providing self-service support options.
- Minimizes support inquiries by enabling users to find answers independently.
- Enhances user confidence and satisfaction by clarifying app functionality and security.

---

**Please assign this issue to GSSoC'24 ext and Hacktoberfest labels.** @Shreyaa173

**Comment by Shreyaa173** [comment]
Assign to you
