### ISSUE TITLE
Design a landing page for signup and login

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [Shreyaa173/Code-Book#4]
Currently the signup and login buttons don't work.
Solution:
To develop a signup and login page.
Please assign the issue to me under gssoc.

**Comment by Shreyaa173** [comment]
Please make sure that you make the login and signup page as per the theme of the website

**Comment by ayush-py-c** [comment]
I hope you're doing well! I’d like to work on the issue #4 Design a landing page for signup and login
 . Could you please assign it to me? I believe I can make meaningful progress

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..
