### ISSUE TITLE
update the exisiting readme.md file

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [Shreyaa173/Code-Book#40]
It lack guidelines and license section
Also we can add few more related to the project details and enhance the vocabulary 

(Please add gssoc-ext 24 and hacktoberfest label)

**Comment by WebWizard2965** [comment]
I can solve this if you assign me this issue

**Comment by AKSHITHA-CHILUKA** [comment]
@Shreyaa173  May I know the reason why you closed the issue

**Comment by Shreyaa173** [comment]
As I am already working on it
