### ISSUE TITLE
Too Many Imports From Same Directory

### ISSUE THREAD

**Issue by AngadSudan** [Shreyaa173/Code-Book#43]
There are too many imports in the app.jsx Which increases the Line Of Code (LOC) and is not a good practice to do so.

![image](https://github.com/user-attachments/assets/8c6ba9e8-f92c-4d79-a251-98140470f25e)

Possible Fix- Adding an index file to improve the Import Commands and reducing LOC.

**Comment by AngadSudan** [comment]
If you like the proposal, I'd be happy to work on the issue.

**Comment by Shreyaa173** [comment]
Assigned to you

**Comment by AngadSudan** [comment]
Working on it.
