### ISSUE TITLE
error in signup 

### ISSUE THREAD

**Issue by AyushSharma72** [Shreyaa173/Code-Book#437]
there is an error in signup 
![image](https://github.com/user-attachments/assets/5b63f231-265e-4e67-a7af-cb47fb2e588f)

![image](https://github.com/user-attachments/assets/69571983-39cf-47b3-b7e1-e1dac41c5ab6)

please assign this issue to me @Shreyaa173

**Comment by Shreyaa173** [comment]
It's something I have to do as it is in deployment as it runs in the localhost.

**Comment by AyushSharma72** [comment]
> It's something I have to do as it is in deployment as it runs in the localhost.

No it's a cors error
