### ISSUE TITLE
Improve the UI/UX of the website

### ISSUE THREAD

**Issue by Aryan-01-star** [Shreyaa173/Code-Book#438]
I think we can take the current UI of the website to a better version of itself and make it more appealing for the viewer which can result in a better User Experience (UX) and an overall increased engagement time of the user. 

Screen Shot of the problem area:
 
![image](https://github.com/user-attachments/assets/60748dd9-ee05-4e29-b619-daa470fffe68)

**Comment by Karna0005** [comment]
assign it to me, i would love to contribute!
