### ISSUE TITLE
Log-in Sign-up page

### ISSUE THREAD

**Issue by dushyantkanav** [Shreyaa173/Code-Book#44]
i can resolve this issue

**Comment by Ayush1Deshmukh** [comment]
I can add it with responsiveness , so please assign it to me

**Comment by yogendrakag** [comment]
I see that the login/signup section is missing in this project. As a contributor to GSSoC '24 extended program, I would love to work on this issue. Could you please assign it to me?"

**Comment by Shreyaa173** [comment]
assigned to you
