### ISSUE TITLE
Improving Component Reusability

### ISSUE THREAD

**Issue by AngadSudan** [Shreyaa173/Code-Book#45]
The same component is being used again and decreasing the Code Quality.

![image](https://github.com/user-attachments/assets/e1435961-b144-463c-a205-9f843093a20d)

Fix- Adding the same component using map function of javascript making the code Scalable.

**Comment by AngadSudan** [comment]
I'd like to help with this Code.

**Comment by Shreyaa173** [comment]
assigned to you

**Comment by AngadSudan** [comment]
Working on it.
