### ISSUE TITLE
 💥💥 Tagging Discrepancy: Level 2 and GSSOC Label Missing

### ISSUE THREAD

**Issue by akash70629** [Shreyaa173/Code-Book#452]
@Shreyaa173 I'm reporting an issue regarding inconsistent tagging and missing GSSOC,level 2 tag for Pull Request #384, which resolved Issue #379. Initially, Issue #379 was labelled as Level 2, but after submitting PR #384, the label was changed to Level 1 without explanation. Furthermore, no GSSOC, level 2 tag was added after merging PR #384. I kindly request that the label for Issue #379 be reverted to Level 2, reflecting its original severity and that the GSSOC tag be added to PR #384, as accurate tagging is crucial for tracking progress and points in the GSSOC competition.

**Comment by Shreyaa173** [comment]
Sorry for the issue as I didn't checked for my mails from a long time as I have something going on.

**Comment by Shreyaa173** [comment]
I've added all the labels

**Comment by akash70629** [comment]
> Sorry for the issue as I didn't checked for my mails from a long time as I have something going on.

@Shreyaa173 No worries about the delay !! Life can get busy and overwhelming, and it's completely understandable that you haven't been able to check your emails. Hope now everything is okay and that you're doing well.

**Comment by akash70629** [comment]
> I've added all the labels

Thank You !😊🌸

**Comment by Shreyaa173** [comment]
Thanks for understanding😊
