### ISSUE TITLE
Improve Spacing of the Navbar

### ISSUE THREAD

**Issue by Devaki01** [Shreyaa173/Code-Book#462]
Hello, 
I would like to contribute by improving the spacing between the navlinks of the Navbar to make it more structured and organised. 
<img width="959" alt="image" src="https://github.com/user-attachments/assets/ef9f948d-211c-485f-91c7-de369deefb39">

Please assign me this under ggsoc'24 extd.

**Comment by pujasharma004** [comment]
I would like to contribute in that .kindly requested to assign me this project
