### ISSUE TITLE
ADD Social Media Links to the Footer of README

### ISSUE THREAD

**Issue by amiya-cyber** [Shreyaa173/Code-Book#465]
Add a visually appealing footer to the README that includes links to key social media profiles, making it easy for users to connect and stay updated. The footer should align with the project's branding, feature accessible icons (e.g., GitHub, Twitter, LinkedIn), and be mobile-friendly. Each link must be verified to open correctly, ideally in a new tab where possible. This enhancement will improve user engagement and provide quick access to our social platforms.

![2024-11-01 (6)](https://github.com/user-attachments/assets/94772b70-2359-42c1-ba5f-4a7b63a1ad94)

**Comment by abhipsa14** [comment]
@amiya-cyber assign this issue to me
