### ISSUE TITLE
sign up page and log-in page is not opening

### ISSUE THREAD

**Issue by Nitish6391920700** [Shreyaa173/Code-Book#48]
sign up page and log-in page is not opening

**Comment by Dagi2004** [comment]
I can work on this one please

**Comment by ar1701** [comment]
Can you provide more details on it ? and assign it to me

**Comment by tanushrigoel** [comment]
@Shreyaa173 @Vaibhav-Kumar-K-R please assign this to me. I would love to work on it.

**Comment by Nitish6391920700** [comment]
I am working on it

**Comment by Shreyaa173** [comment]
Assigned to you @Nitish6391920700

**Comment by Nitish6391920700** [comment]
In this repositories route is not setup if you allow me the i set route. this will change your App.jsx structure
