### ISSUE TITLE
Create about us page 

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [Shreyaa173/Code-Book#5]
Currently the about us information is displayed in the footer
Solution
An About us page can be created and linked 
Please assign this issue to me GSSOC'24
![image](https://github.com/user-attachments/assets/a81a5410-cd1b-415c-b491-f095e1879340)

**Comment by rutikakengal** [comment]
Add about us section to the page which gives information regarding this website ,Assign me i loved to work on this

**Comment by Shreyaa173** [comment]
The about us is already done in the landing page so not needed
