### ISSUE TITLE
Navbar links scrollTo not working correctlty.

### ISSUE THREAD

**Issue by RchtDshr** [Shreyaa173/Code-Book#52]
Navbar options (Courses, Testimonials, Contact) not scrolling to the correct section of the page. Also, due to the height of the navbar the scrollTo should leave some space above so that the contents of navbar and contents of the sections do not get overlapped. The scrollTo for contact is not working correctly.

I can fix this issue. Please assign me this task under gsscoc-24-ext and hacktoberfest

**Comment by Shreyaa173** [comment]
assigned to you
