### ISSUE TITLE
Add Missing Logo to the Header Section

### ISSUE THREAD

**Issue by saismrutiranjan18** [Shreyaa173/Code-Book#55]
Issue:
The browser tab for the "Code Book" project does not display the logo/favicon. Instead, it shows a default icon. This needs to be fixed so that the custom logo is visible in the tab, as shown in the attached screenshots.

Project Reference:
URL: code-book-kappa.vercel.app
Related event tags: @GSSoC-Ext @Hacktoberfest

Proposed Solution:
Add a favicon by converting the current logo into an appropriate format (favicon.ico).
Update the HTML to include a <link> tag in the <head> section that points to the favicon.
Ensure that the favicon is placed in the correct public directory.

Intent:
I would like to contribute and fix this issue by implementing the above solution.

Attachments:
![Screenshot 2024-10-03 001238](https://github.com/user-attachments/assets/71874d72-0005-4065-bf99-85c6cc3b9853)

This is the logo which i want to put in the header section or logo part

![Screenshot 2024-10-03 001117](https://github.com/user-attachments/assets/b3c51715-a4ce-43f1-9c5d-7957dd658d8c)

**Comment by Rashmi885** [comment]
Pls assign this issue to me under GSSOC
