### ISSUE TITLE
Add Light-Dark mode

### ISSUE THREAD

**Issue by prasoonk1204** [Shreyaa173/Code-Book#56]
Currently the website has only dark mode, I would like to make a light mode interface for it and a toggle in the navbar to switch between them. 

please assign it to me, so i can start the work.

also add **gssoc-ext**, **hactoberfest-accepted** and **level** (**1/2/3** -- based on what you think is the difficulty of this task) labels.

**Comment by sambedan1** [comment]
i have a great knowledge about it please assign it to me

**Comment by prasoonk1204** [comment]
hello @Shreyaa173, may i know why did you closed this?

**Comment by AnshuWorld** [comment]
Please assign me this task under gssoc24 extd
