### ISSUE TITLE
 Add Course Redirection to YouTube Playlists or Course Material or Creators's Channel

### ISSUE THREAD

**Issue by sanyadureja** [Shreyaa173/Code-Book#58]
The current course cards on the website do not have interactive elements that redirect users to the respective course playlists, channels, or YouTube resources. I propose adding functionality to each course card so that clicking on a course redirects users to:
 
- The specific YouTube playlist for the course.
- The full course page (if available).
- The YouTuber's or course creator's YouTube channel.

This will enhance the user experience by providing direct access to additional learning materials.

Proposed Solution:

- Add clickable links to each course card.
- Implement the redirection to either the course playlist or the creator's channel.
- Ensure the links open in a new tab for smooth navigation.

**Comment by sanyadureja** [comment]
@Shreyaa173 If you find this idea suitable, please assign it to me as part of GSSoC'24 Extended, along with appropriate labels. As a beginner in open source contributions, this would be a fantastic opportunity for me. I look forward to your response.

Thank you!

**Comment by sanyadureja** [comment]
@Shreyaa173 Please assign it to me as part of GSSoC'24 Extended.

**Comment by Shreyaa173** [comment]
assigned to you

**Comment by Ayush07571** [comment]
Please assign this issue to me

**Comment by sanyadureja** [comment]
> Please assign this issue to me

I've already completed this issue, my PR has been merged. You can work on some other issue.
