### ISSUE TITLE
Contact Us Form Issue

### ISSUE THREAD

**Issue by Kajolshah29** [Shreyaa173/Code-Book#6]
Misalignment: The phone number input field appears misaligned with the rest of the form elements. 

Non-Functional Submit Button: Clicking the submit button does not trigger any action. There is no indication to the user that their submission has been received or processed.

Please assign the issue to me.

**Comment by Shreyaa173** [comment]
Make sure you star the repo for further proceeding.

**Comment by akdwivedi-explorer** [comment]
I can help you. Please assign this to me.

**Comment by GULSHANITSYOU** [comment]
@Shreyaa173, you didn't provide a reason for closing my PR. Sorry!

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..
