### ISSUE TITLE
Fix : Readjusting and enhancing Website title in Header(navbar)

### ISSUE THREAD

**Issue by iamsaura8h** [Shreyaa173/Code-Book#64]
hey @Shreyaa173 

i would like to **Enhance** **Website Title** for Better branding and visibility , since there is no **padding or margin** here , i would also love to style it using suitable fonts which matches the whole website theme and make it more appealing.

<img width="960" alt="is4" src="https://github.com/user-attachments/assets/e352650b-216b-43ce-a52c-5e76e38ed4b7">

### please assign me this issue with `gssoc-ext` label , i am a UI/UX designer so this means much to me as it as important for any website.

thank you

**Comment by sambedan1** [comment]
assign this project to me
