### ISSUE TITLE
Footer part of website 

### ISSUE THREAD

**Issue by Codersweta7** [Shreyaa173/Code-Book#7]
I want to work upon footer part of website such as home , About us , FAQ/help , privacy policy and terms of service , including subscribe to our newsletter , and connect with us 

Please assign this part to me under gssoc extd'2024

**Comment by Codersweta7** [comment]
Thankyou Shreya , this is going to be my first contribution and I am very
excited to do that 🙂

**Comment by Shreyaa173** [comment]
Make sure you star the repo for further proceeding.

**Comment by ayush-py-c** [comment]
I hope you're doing well! I’d like to work on the issue #7 . Could you please assign it to me? I believe I can make meaningful progress

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..

**Comment by Codersweta7** [comment]
> Make sure you star the repo for further proceeding.

@Shreyaa173 need some help .

**Comment by Shreyaa173** [comment]
Yes??

**Comment by Codersweta7** [comment]
I wanted links for 
Instagram , and other social media platforms including discord .
And I want to ask that for the file home .html what content I should ?? 

> Yes??

**Comment by Ankitaghavate** [comment]
add footer in black color and also link other links like Instagram, facebook, linked in

**Comment by Codersweta7** [comment]
> add footer in black color and also link Social media account like Instagram, facebook, linked in

Yes that part is done 
I have prepare faq.html , privacy page .html  , 
Give me some ideas for home.html 
Should I use section tag and redirect user to index.html or there is new  which I should do to prepare this page

**Comment by Codersweta7** [comment]
@Shreyaa173 ,@Ankitaghavate 
Give me some ideas for home.html and about me.html

**Comment by Ankitaghavate** [comment]
First, create the home.html page, add a picture and a video, and include a welcome message for the Code-Book project 📚. Also, add a 'Get Started' button that directs users to the index.html page when clicked.

**Comment by Codersweta7** [comment]
@Ankitaghavate 
Can you please assign this under gssoc extd' and some level like level 1 or level 2

**Comment by Codersweta7** [comment]
@Ankitaghavate 
The recent pull request made in contact section have affected footer part of this website so much
