### ISSUE TITLE
Add FAQ section

### ISSUE THREAD

**Issue by anushkajjadhav** [Shreyaa173/Code-Book#74]
can add a faq regarding the courses and site

can this be assigned to me

**Comment by Shreyaa173** [comment]
assigned to you

**Comment by Codersweta7** [comment]
@Shreyaa173 
Please assign this issue to me ...

**Comment by sourav349** [comment]
Hey @anushkajjadhav I am interested in this issue ,can you assign this issue too me.

**Comment by sourav349** [comment]
To improve your FAQ section, organize questions by category, use clear language, add a search function, include visuals, update regularly, and provide contact options. Please assign this issue to me.
