### ISSUE TITLE
Add logos for Social Media links in Contact Us section

### ISSUE THREAD

**Issue by prishsha** [Shreyaa173/Code-Book#76]
I would like to add logos of linkedin, github etc. in the contact us section of the page to enhance the visual appeal. I would also like to redirect the user to the particular link. Kindly assign me this issue under the label gssoc-ext and hacktoberfest-accepted specifying the level of the probkem. Thank you!

**Comment by SatyaD012** [comment]
Hello,
I'd like to work on this issue. Please assign it to me.
P.S: Please add gssoc-ext and hactoberfest-accepted labels
