### ISSUE TITLE
adding quiz testing for taking a course.

### ISSUE THREAD

**Issue by SoumyaU25** [Shreyaa173/Code-Book#8]
I want to add a quiz test system  for each and every topic available in the web site which will tell  a student based upon their performance in a certain topic  that he/she is at beginner , Intermediate or advance level and on that basis the Student can decide that  which course is preferable for them. It will make the site more Interactive for users.

Please assign this issue to me as I would like to help in ensuring better Interactive website for learning purpose. Please add relevant labels GSSoC 2024 Extd.

**Comment by Shreyaa173** [comment]
Make sure you star the repo for further proceeding.

**Comment by SoumyaU25** [comment]
Ofcourse I will. Can you Please add  labels GSSoC 2024 Extd.

**Comment by SoumyaU25** [comment]
hello @Shreyaa173 can you add gssoc-ext label.
