### ISSUE TITLE
[Feature Enhancement] : ✨Dark mode toggle ✨ 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Shreyaa173/Code-Book#85]
I can work on this feature and make a user interactive dark mode toggle , can you please assign me this task? 
Thank you!

**Comment by T-Rahul-prabhu-38** [comment]
yea i will make a toggle to switch btw dark and light mode.

**Comment by Shreyaa173** [comment]
assigned to you

**Comment by T-Rahul-prabhu-38** [comment]
ill work on this right away .

**Comment by Shreyaa173** [comment]
yep
