### ISSUE TITLE
Enhancing Responsiveness for everything  and switching to svg instead of images 

### ISSUE THREAD

**Issue by abhishekpanthee** [Shreyaa173/Code-Book#89]
It seemed pretty defaming how unresponsive and  unregularized the website is and is a prefect opportunity to  contribute  for everyone . 
so I want to contribute to diving sections and improving ui  of every section and the main issue of image unresponsiveness is really  hampered the ui so switiching to svg i want to contribute to that 
 conclusion 
 - different section for each title 
 - a bit more ux friendly footer 
 - optimized fonts and texts 
 - resounded form section  
 - switching img to svg for better presentation

**Comment by Shreyaa173** [comment]
assigned to you
