### ISSUE TITLE
Adding welcome prompt or chatbot

### ISSUE THREAD

**Issue by tanya-soni-git** [Shreyaa173/Code-Book#9]

**Comment by Shreyaa173** [comment]
Make sure you star the repo for further proceeding.

**Comment by PadmasreeSangani** [comment]
Hi @tanya-soni-git,

I would like to work on adding the welcome prompt or chatbot feature. My aim is to create a user-friendly experience to assist users effectively.

**Comment by PadmasreeSangani** [comment]
Hi @tanya-soni-git,

I would like to work on adding the welcome prompt or chatbot feature. My aim is to create a user-friendly experience to assist users effectively.

**Comment by tanya-soni-git** [comment]
Hi @PadmasreeSangani so should we collaborate and work on same?

**Comment by PadmasreeSangani** [comment]
Hi @tanya-soni-git 

Thank you for reaching out! I'd love to collaborate and work on this project together. Let's discuss the details and figure out how we can contribute effectively as a team. Looking forward to it!

**Comment by tanya-soni-git** [comment]
Sure @PadmasreeSangani if @Shreyaa173 assigns the issue to us as a team.
