### ISSUE TITLE
want to add better logo for all the languages 

### ISSUE THREAD

**Issue by ritikm31** [Shreyaa173/Code-Book#93]
i want to add a better proportion logo for the all languages card.

**Comment by HimanshuM685** [comment]
Assign me

**Comment by biswa2005** [comment]
please assign to me

**Comment by ritikm31** [comment]
thanks for the assign

**Comment by ritikm31** [comment]
sorry for the wait i'm gonna working on it now.

**Comment by ritikm31** [comment]
why this pr isn't shown in my leaderboard can you explain it please
