### ISSUE TITLE
Feature Request: Coding Practice Section

### ISSUE THREAD

**Issue by SonaGaud** [Shreyaa173/Code-Book#94]
I propose adding a new section titled "Coding Practice" or integrating it under the current resources. This section will provide links to platforms where beginners can practice coding in a hands-on manner, such as interactive coding websites or tutorials (leetcode, etc.). It will help users gain practical experience while learning, which is essential for building confidence and preparing for real-world coding tasks.

**Comment by SonaGaud** [comment]
Thank you Shreya173

**Comment by rudrapratap63** [comment]
Hello @SonaGaud do you currently working on this issue ?

**Comment by SonaGaud** [comment]
> Hello @SonaGaud are you currently working on this issue ? 
> 

Yes I just started working on this issue
