### ISSUE TITLE
Want to Improve the Hero section of this site

### ISSUE THREAD

**Issue by kanCHI-Singhal** [Shreyaa173/Code-Book#99]
Hey! @Shreyaa173 , My self Kanishka Singhal.
On reviewing this site I want to change the hero section of this site , I want to add sliding carousels in the hero section with amazing images and videos. which improves the user experience and makes the UI more attractive.
Please assign me this issue under the labels of Gssoc-extd, hacktoberfest, hacktoberfest-accepted and relevant level also please assign me the level of this issue as well .

**Comment by Shreyaa173** [comment]
Not needed
